const SET_FILTER_TYPE = "SET_FILTER_TYPE";
const SET_FILTER_VARIANT_CLASS = "SET_FILTER_VARIANT_CLASS";
const SET_FILTER_SOMATIC_CLASS = "SET_FILTER_SOMATIC_CLASS";
const SET_FILTER_HOT_SPOT = "SET_FILTER_HOT_SPOT";
const SET_FILTER_SNP = "SET_FILTER_SNP";
const SET_FILTER_ROI = "SET_FILTER_ROI";
const SET_FILTER_CANCER_DBS = "SET_FILTER_CANCER_DBS";
const SET_FILTER_GNOM_ID = "SET_FILTER_GNOM_ID";

export default {
  SET_FILTER_TYPE,
  SET_FILTER_VARIANT_CLASS,
  SET_FILTER_SOMATIC_CLASS,
  SET_FILTER_HOT_SPOT,
  SET_FILTER_SNP,
  SET_FILTER_ROI,
  SET_FILTER_CANCER_DBS,
  SET_FILTER_GNOM_ID
};
