// filters
const SET_FILTER_TYPE = "SET_FILTER_TYPE";
const SET_FILTER_VARIANT_CLASS = "SET_FILTER_VARIANT_CLASS";
const SET_FILTER_SOMATIC_CLASS = "SET_FILTER_SOMATIC_CLASS";
const SET_FILTER_HOT_SPOT = "SET_FILTER_HOT_SPOT";
const SET_FILTER_SNP = "SET_FILTER_SNP";
const SET_FILTER_ROI = "SET_FILTER_ROI";
const SET_FILTER_VAF = "SET_FILTER_VAF";
const SET_FILTER_CANCER_DBS = "SET_FILTER_CANCER_DBS";
const SET_FILTER_GNOM_ID = "SET_FILTER_GNOM_ID";
const GET_FILTERED_DATA = "GET_FILTERED_DATA";

// table
const SELECT_ROW_KEY = "SELECT_ROW_KEY";
const HANDLE_ZYGOSITY = "HANDLE_ZYGOSITY";
const HANDLE_VARIANT_CLASS = "HANDLE_VARIANT_CLASS";

// variants
const SET_MUTATION_TYPE = "SET_MUTATION_TYPE";
const SET_NOTES = "SET_NOTES";

export default {
  // filters
  SET_FILTER_TYPE,
  SET_FILTER_VARIANT_CLASS,
  SET_FILTER_SOMATIC_CLASS,
  SET_FILTER_HOT_SPOT,
  SET_FILTER_SNP,
  SET_FILTER_ROI,
  SET_FILTER_VAF,
  SET_FILTER_CANCER_DBS,
  SET_FILTER_GNOM_ID,
  GET_FILTERED_DATA,

  // table
  SELECT_ROW_KEY,
  HANDLE_ZYGOSITY,
  HANDLE_VARIANT_CLASS,

  // variants
  SET_MUTATION_TYPE,
  SET_NOTES,
};
